channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.1.1
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.3.0
  - scipy==1.16.1
name: mlflow-env